Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      HelmChartArtifactRelation:
        '{{computenest::helmchart::chartUrl}}': 
          ArtifactId: artifact-xxx
          ArtifactVersion: draft
    TemplateConfigs:
      - Name: ack
        Url: 'templates/template.yaml'
        AllowedRegions: []
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    Image: 'icons/service_logo.png'
    Name: Helm私有化部署
  ShareType: Public
  ApprovalType: Manual