ROSTemplateFormatVersion: '2015-09-01'
# 定义参数
Parameters:
  Parameters:
    Type: Json
    AssociationProperty: List[Parameters]
    AssociationPropertyMetadata:
      Parameters:
        Name:
          Type: String
        Label:
          Type: String
        Type:
          Type: String
          AllowedValues:
            - Integer
            - String
            - Boolean
            - Json
        AllowedValues:
          Type: Json
          AssociationProperty: List
          AssociationPropertyMetadata:
            Multiple: true
          Default: Null
          Required: false
        NoEcho:
          Type: Boolean
          Default: false
          AllowedValues:
            - true
            - false
        AssociationProperty:
          Type: String
          Default: Null
          Required: false
          AssociationProperty: AssociationProperty
  ReleaseName:
    Type: String
    Default: helm
  HelmArtifactId:
    Type: String
    Label:
      en: helm artifact
      zh-cn: helm部署物
    AssociationProperty: ALIYUN::ComputeNest::Artifact::ArtifactId
    AssociationPropertyMetadata:
      IsSupplier: true
      ArtifactType: HelmChart
  HelmArtifactVersion:
    Type: String
    Label:
      en: helm artifact
      zh-cn: helm部署物版本
    AssociationProperty: ALIYUN::ComputeNest::Artifact::ArtifactIdVersion
    AssociationPropertyMetadata:
      IsSupplier: true
      ArtifactId: ${HelmArtifactId}
  Values:
    Type: String
    AssociationProperty: Json
    Default:
      service:
        type: LoadBalancer
      postgresql:
        enabled: true
        adminPassword:
          Ref: AdminPassword
        primary:
          persistence:
            enabled: true
            storageClass: alicloud-disk-essd
            size: 40Gi
  Outputs:
    Type: Json
    AssociationProperty: List[Parameters]
    AssociationPropertyMetadata:
      Parameters:
        Kind:
          Type: String
          AllowedValues:
            - Service
            - Deployment
            - StatefulSet
            - ConfigMap
            - Ingress
        Name:
          Type: String
        Label:
          Type: String
        JsonPath:
          Type: String
        Expression:
          Type: String
    Default:
      - Kind: Service
        Name: harbor-server
        Label: Endpoint
        JsonPath: $.status.loadBalancer.ingress[0].ip
        Expression: https://${OutputValue}:8080
Metadata:
  ALIYUN::ROS::Interface:
    # 定义资源分组，创建服务实例时，同一分组的参数分布在一起
    ParameterGroups:
      - Parameters:
          - Label: Helm部署物
            Items:
              - HelmArtifactId
              - HelmArtifactVersion
          - ReleaseName
          - Parameters
          - Values
        Label:
          en: Deployment Configuration
          zh-cn: 部署配置
      - Parameters:
          - Outputs
        Label:
          en: Deployment Configuration
          zh-cn: 输出配置