ROSTemplateFormatVersion: '2015-09-01'
# 定义参数
Parameters:
  Parameters:
    Type: Json
    AssociationProperty: Json
    Default:
    - Name: AdminPassword
      NoEcho: true
      Type: String
      Label: 管理员密码
      AssociationProperty: ALIYUN::ECS::Instance::Password
  ReleaseName:
    Type: String
    Default: helm
  HelmArtifactId:
    Type: String
    Label:
      en: helm artifact
      zh-cn: helm部署物
    AssociationProperty: ALIYUN::ComputeNest::Artifact::ArtifactId
    AssociationPropertyMetadata:
      IsSupplier: true
      ArtifactType: HelmChart
  HelmArtifactVersion:
    Type: String
    Label:
      en: helm artifact
      zh-cn: helm部署物版本
    AssociationProperty: ALIYUN::ComputeNest::Artifact::ArtifactIdVersion
    AssociationPropertyMetadata:
      IsSupplier: true
      ArtifactId: ${HelmArtifactId}
  Values:
    Type: String
    AssociationProperty: Json
    Default:
      service:
        type: LoadBalancer
      postgresql:
        enabled: true
        adminPassword:
          Ref: AdminPassword
        primary:
          persistence:
            enabled: true
            storageClass: alicloud-disk-essd
            size: 40Gi
  Outputs:
    Type: Json
    AssociationProperty: Json
    Default:
      - Kind: Service
        Name: harbor-server
        Label: Endpoint
        JsonPath: $.status.loadBalancer.ingress[0].ip
        Expression: https://${OutputValue}:8080
Metadata:
  ALIYUN::ROS::Interface:
    # 定义资源分组，创建服务实例时，同一分组的参数分布在一起
    ParameterGroups:
      - Parameters:
          - HelmArtifactId
          - HelmArtifactVersion
          - ReleaseName
          - Parameters
          - Values
        Label:
          en: Deployment Configuration
          zh-cn: 部署配置
      - Parameters:
          - Outputs
        Label:
          en: Deployment Configuration
          zh-cn: 输出配置